include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-inference: false
    strict-raw-types: false
  # errors:
  #   # treat missing required parameters as a warning (not a hint)
  #   missing_required_param: error
  #   # treat missing returns as a warning (not a hint)
  #   missing_return: error
  #   # allow having TODOs in the code
  #   todo: ignore
  #   # allow self-reference to deprecated members (we do this because otherwise we have
  #   # to annotate every member in every test, assert, etc, when we deprecate something)
  #   deprecated_member_use_from_same_package: warning
  #   # ignore sentry/path on pubspec as we change it on deployment
  #   invalid_dependency: ignore
  #   inference_failure_on_function_invocation: ignore

linter:
  rules:
    prefer_relative_imports: true
    avoid_classes_with_only_static_members: true
    always_use_package_imports: false
    cascade_invocations: false
    flutter_style_todos: false
    lines_longer_than_80_chars: false
    no_default_cases: false
    public_member_api_docs: false
    sort_constructors_first: false
    sort_unnamed_constructors_first: false
    use_setters_to_change_properties: false
    use_build_context_synchronously: false
    avoid_positional_boolean_parameters: false
    comment_references: false
    prefer_asserts_with_message: false